# Generated by Django 5.1.2 on 2024-11-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=60)),
                ('short_info', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(choices=[('KS', 'Кибербезопасность'), ('IP', 'Импортозамещение в программном обеспечении'), ('BD&II', 'Большие данные и искусственный интеллект')], max_length=5)),
                ('topic', models.CharField(max_length=200)),
                ('workbar', models.IntegerField(default=0)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytest.members')),
            ],
        ),
    ]
