# Generated by Django 5.1.2 on 2024-11-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='project_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mytest.project'),
        ),
    ]
